### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by webstations** [klokantech/tileserver-php#126]
I have a 66 .mbtile file.
of the 66 files I uploaded to the server, many of which can not open with HTTP ERROR 500 error messages.
for example can be opened address https: ///maps.ptsljakbar.com/{number 1 to 66}/

error messages obtained from the wrong log are as follows:
(sample from https: ///maps.ptsljakbar.com/13/)

[05-Apr-2018 13:39:42 UTC] PHP Fatal error:  Uncaught Error: Call to a member function fetchAll() on boolean in /home/bpnjakba/maps.ptsljakbar.com/13/tileserver.php:189
Stack trace:
#0 /home/bpnjakba/maps.ptsljakbar.com/13/tileserver.php(104): Server->metadataFromMbtiles('JELAMBAR_BARU.m...')
#1 /home/bpnjakba/maps.ptsljakbar.com/13/tileserver.php(537): Server->setDatasets()
#2 /home/bpnjakba/maps.ptsljakbar.com/13/tileserver.php(1285): Server->getHtml()
#3 /home/bpnjakba/maps.ptsljakbar.com/13/tileserver.php(18): Router::serve(Array)
#4 {main}
  thrown in /home/bpnjakba/maps.ptsljakbar.com/13/tileserver.php on line 189

can you help me, why this error happened

**Comment by webstations** [comment]
yes, i have PHP SQLite installed, as you can see in https://maps.ptsljakbar.com/1/ or https://maps.ptsljakbar.com/4/ as sample. running on PHP 5.6 ver

**Comment by daliborjanak** [comment]
My mistake. So PHP and tileserver are OK. It might be a wrongly copied or broken files or some collision with rewrites. You have tileserver also on https://maps.ptsljakbar.com/. And if there is an htaccess there it might handle some URL to this root which cannot find the file.

**Comment by webstations** [comment]
I convert the all shp file into mbtiles using tilemill, i tried to recreate the mbfiles which not opened (as sample at https: ///maps.ptsljakbar.com/13/ ) and upload again to server, but still failed to open (error 500).

i tried delete .htaccress file and tileserver file on root and still not work.

**Comment by webstations** [comment]
[samplembtiles.zip](https://github.com/klokantech/tileserver-php/files/1880550/samplembtiles.zip)

i attach sample mbtiles that work ang not work
