### ISSUE TITLE
Error on default install

### ISSUE THREAD

**Issue by e-tinchux** [klokantech/tileserver-php#132]
Hi falks!  I'm getting this error ... can you give me a hand?

Regards!

#0 /var/www/html/maptiles/tileserver.php(300): PDO->__construct('sqlite:2017-07-...', '', '', Array)
#1 /var/www/html/maptiles/tileserver.php(186): Server->DBconnect('2017-07-03_arge...')
#2 /var/www/html/maptiles/tileserver.php(104): Server->metadataFromMbtiles('2017-07-03_arge...') 
#3 /var/www/html/maptiles/tileserver.php(537): Server->setDatasets()
#4 /var/www/html/maptiles/tileserver.php(1285): Server->getHtml()
#5 /var/www/html/maptiles/tileserver.php(18): Router::serve(Array) 
#6 {main}

**Comment by e-tinchux** [comment]
I trying to install with apache2 ans php 7.2

**Comment by e-tinchux** [comment]
Thanks! Yes ..but I must configure something in tileserver.php file?

Regards!

**Comment by e-tinchux** [comment]
It is working now. PHP 7.1 works without problems
